micronaut:
  application:
    name: dealership_program
datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
flyway:
  datasources:
    default:
      enabled: true
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
netty:
  default:
    allocator:
      max-order: 3
coherence.session.default.type: grpc
